Repository ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta, pull requests merged in 2023-11, with the labels that each got.

#155 [RF-13] - Histórias de Sucesso
  src/assets/images/man-smiling.jpg
  src/assets/images/older-man.jpg
  src/assets/images/people-working.jpg
  src/assets/images/persona 1.jpg
  src/assets/images/woman-with-computer.jpg
  src/assets/images/woman-with-kids.jpg
  src/pages/historias-sucesso/historias-sucesso.css
  src/pages/historias-sucesso/historias-sucesso.html
  src/pages/sobre-o-voluntariado/sobre_o_voluntariado.html
Labels: enhancement

#156 Adiciona página Administrar Demandas
  docs/img/icons/delete.png
  docs/img/icons/edit.png
  src/pages/administrar-demandas/administrar-demandas.css
  src/pages/administrar-demandas/administrar-demandas.html
Labels: enhancement

#154 [RF-20] - Cadastrar depoimento
  src/pages/cadastrar-depoimento/cadastrar-depoimento.css
  src/pages/cadastrar-depoimento/cadastrar-depoimento.html
Labels: enhancement

#153 [RF-05] - Candidatar-se a uma demanda
  src/pages/candidatar-a-demanda/candidatar-a-demanda.css
  src/pages/candidatar-a-demanda/candidatar-a-demanda.html
Labels: enhancement

#151 Sugestões em estrutura de dados
  docs/development.md
Labels: documentation

#145 Estruturas de dados
  docs/development.md
Labels: documentation

#168 Move botão de fechar o menu mobile para o canto direito
  src/components/header/header.css
Labels: enhancement

#158 Cria página de redefinição de senha
  src/pages/recuperar-senha/recuperar-senha.css
  src/pages/recuperar-senha/recuperar-senha.html
  src/pages/recuperar-senha/recuperar-senha.js
Labels: enhancement

#169 Adiciona tipo de voluntariado
  docs/img/icons/location.png
  src/pages/pagina-de-demandas/pagina-de-demandas.css
  src/pages/pagina-de-demandas/pagina-de-demandas.html
Labels: enhancement

#160 Correção historias de sucesso
  src/pages/historias-sucesso/historias-sucesso.css
Labels: enhancement

#159 Adiciona Landing Page
  src/assets/images/1.png
  src/assets/images/2.png
  src/assets/images/3.png
  src/assets/images/home-image-one-mobile.jpg
  src/assets/images/home-image-one.jpg
  src/assets/images/home-image-three-mobile.jpg
  src/assets/images/home-image-three.jpg
  src/assets/images/home-image-two-mobile.jpg
  src/assets/images/home-image-two.jpg
  src/assets/images/team-working.png
  src/components/header/header.js
  src/index.html
  src/js/landing-page.js
  src/pages/landing-page/landing-page.css
Labels: enhancement

#139 Pagina por que ser voluntario
  src/assets/images/porque-ser-voluntario.png
  src/pages/por-que-ser-voluntario/por-que-ser-voluntario.css
  src/pages/por-que-ser-voluntario/por-que-ser-voluntario.html
Labels: enhancement

#152 Tela cadastrar demanda da ong
  src/pages/cadastrar-demanda/cadastrar-demanda.css
  src/pages/cadastrar-demanda/cadastrar-demanda.html
Labels: enhancement

#192 [RF-XX] - Login
  src/components/header/header.js
  src/pages/login/login.css
  src/pages/login/login.html
  src/pages/login/login.js
Labels: enhancement

#193 Correcao src porque ser voluntario
  src/components/footer/footer.js
  src/pages/por-que-ser-voluntario/por-que-ser-voluntario.html
Labels: enhancement

#185 Adiciona pagina de demandas finalizada
  src/assets/icons/message.png
  src/components/vertical-task-card/vertical-task-card.js
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.css
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.html
Labels: enhancement

#197 Adiciona o link para cadastrar demanda.
  src/pages/administrar-demandas/administrar-demandas.html
Labels: enhancement

#198 Correcao paginas
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.css
  src/pages/administrar-demandas/administrar-demandas.css
  src/pages/administrar-demandas/administrar-demandas.html
  src/pages/historias-sucesso/historias-sucesso.css
  src/pages/historias-sucesso/historias-sucesso.html
Labels: enhancement

#201 Ações em cadastrar demanda e Constants
  src/js/constants.js
  src/pages/cadastrar-demanda/cadastrar-demanda.html
  src/pages/cadastrar-demanda/cadastrar-demanda.js
Labels: enhancement

#203 Adiciona link para candidatar-se a demanada aos cards.
  src/components/horizontal-task-card/horizontal-task-card.js
  src/index.html
  src/pages/pagina-de-demandas/pagina-de-demandas.html
Labels: enhancement

#204 Adiciona validações e ações a tela de Candidatar-se a uma demanda.
  src/js/constants.js
  src/pages/candidatar-a-demanda/candidatar-a-demanda.html
  src/pages/candidatar-a-demanda/candidatar-a-demanda.js
Labels: enhancement

#205 Trata links em administrar demandas.
  src/pages/administrar-demanda-em-progresso/administrar-demanda-em-progresso.html
  src/pages/administrar-demandas/administrar-demandas.css
  src/pages/administrar-demandas/administrar-demandas.html
Labels: enhancement

#186 ajuste de tamanho dos formularios
  src/components/header/header.js
  src/pages/cadastrar-demanda/cadastrar-demanda.css
  src/pages/cadastrar-demanda/cadastrar-demanda.html
  src/pages/cadastrar-depoimento/cadastrar-depoimento.css
  src/pages/cadastrar-depoimento/cadastrar-depoimento.html
  src/pages/cadastrar-ong/cadastrar-ong.css
  src/pages/candidatar-a-demanda/candidatar-a-demanda.css
  src/pages/candidatar-a-demanda/candidatar-a-demanda.html
  src/pages/login/login.css
  src/pages/recuperar-senha/recuperar-senha.css
Labels: enhancement

#206 Links adm demandas
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.html
  src/pages/administrar-demandas/administrar-demandas.html
  src/pages/cadastrar-demanda/cadastrar-demanda.html
  src/pages/cadastrar-demanda/cadastrar-demanda.js
Labels: enhancement

#199 Adiciona programacao de funcionalidades
  docs/development.md
Labels: documentation

#207 Adiciona Status Demanda
  src/assets/icons/green-dot.png
  src/assets/icons/red-dot.png
  src/pages/administrar-demanda-em-progresso/administrar-demanda-em-progresso.css
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.css
  src/pages/administrar-demandas/administrar-demandas.css
  src/pages/administrar-demandas/administrar-demandas.html
  src/pages/cadastrar-demanda/cadastrar-demanda.css
  src/pages/cadastrar-depoimento/cadastrar-depoimento.css
  src/pages/cadastrar-ong/cadastrar-ong-2.html
  src/pages/cadastrar-ong/cadastrar-ong.css
  src/pages/como-comecar/como-comecar.html
  src/pages/historias-sucesso/historias-sucesso.css
  src/pages/historias-sucesso/historias-sucesso.html
  src/pages/login/login.css
  src/pages/login/login.html
  src/pages/pagina-da-ong/pagina-da-ong.html
  src/pages/pagina-de-demandas/pagina-de-demandas.html
  src/pages/perguntas-frequentes/perguntas-frequentes.html
  src/pages/por-que-ser-voluntario/por-que-ser-voluntario.html
  src/pages/recuperar-senha/recuperar-senha.css
Labels: enhancement

#209 Adiciona link para pagina da ong.
  src/components/horizontal-task-card/horizontal-task-card.js
  src/components/vertical-task-card/vertical-task-card.js
Labels: enhancement

#208 Define modelo de dados de depoimento.
  docs/development.md
Labels: enhancement

#210 Update formulários
  src/pages/cadastrar-demanda/cadastrar-demanda.css
  src/pages/cadastrar-depoimento/cadastrar-depoimento.css
  src/pages/cadastrar-ong/cadastrar-ong.css
  src/pages/candidatar-a-demanda/candidatar-a-demanda.css
  src/pages/login/login.css
  src/pages/recuperar-senha/recuperar-senha.css
Labels: enhancement

#211 Adiciona definições da coleção de sessões.
  docs/development.md
Labels: documentation

#216 Comunicação HTTP e Objetos de domínio
  .gitignore
  db.json
  package-lock.json
  package.json
  src/js/constants.js
  src/js/http.js
  src/js/models/candidate.js
  src/js/models/organization.js
  src/js/models/review.js
  src/js/models/task.js
  src/js/models/teste.js
  src/teste.html
Labels: enhancement

#218 Envio de email utilizando Javascript
  src/js/envio-email.js
  src/pages/zona-de-testes/envio-email.html
Labels: enhancement

#219 mapeamento de teste
  docs/tests.md
Labels: documentation

#220 adiciona novos RFs
  docs/development.md
  docs/especification.md
  docs/img/wireframes/login.png
  docs/img/wireframes/recuperar-senha.png
  docs/interface.md
Labels: documentation

#238 Adiciona campos de mídias sociais para a estrutura ONG e modifica campo de imagem
  docs/development.md
Labels: documentation, enhancement

#267 Funcionalidade: Cadastrar ONG
  db.json
  docs/tests.md
  src/js/constants.js
  src/js/http.js
  src/js/models/organization.js
  src/pages/cadastrar-ong/cadastrar-ong-1.html
  src/pages/cadastrar-ong/cadastrar-ong-1.js
  src/pages/cadastrar-ong/cadastrar-ong-2.html
  src/pages/cadastrar-ong/cadastrar-ong-2.js
  src/pages/cadastrar-ong/cadastrar-ong.css
Labels: enhancement

#273 Funcionalidade: Página da ONG
  db.json
  docs/tests.md
  src/components/horizontal-task-card/horizontal-task-card.js
  src/components/vertical-task-card/vertical-task-card.js
  src/pages/pagina-da-ong/pagina-da-ong.html
  src/pages/pagina-da-ong/pagina-da-ong.js
Labels: enhancement

#275 Update db.json
  db.json
Labels: enhancement

#277 Adiciona modal nas páginas
  src/assets/icons/NGO.png
  src/assets/icons/voluntary.png
  src/components/horizontal-task-card/horizontal-task-card.js
  src/components/vertical-task-card/vertical-task-card.js
  src/index.html
  src/js/landing-page.js
  src/js/modal.js
  src/pages/administrar-demanda-em-progresso/administrar-demanda-em-progresso.css
  src/pages/administrar-demanda-em-progresso/administrar-demanda-em-progresso.html
  src/pages/administrar-demanda-em-progresso/administrar-demanda-em-progresso.js
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.css
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.html
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.js
  src/pages/administrar-demandas/administrar-demanda.js
  src/pages/administrar-demandas/administrar-demandas.css
  src/pages/administrar-demandas/administrar-demandas.html
  src/pages/cadastrar-demanda/cadastrar-demanda.html
  src/pages/candidatar-a-demanda/candidatar-a-demanda.html
  src/pages/landing-page/landing-page.css
  src/pages/pagina-da-ong/pagina-da-ong.css
  src/pages/pagina-da-ong/pagina-da-ong.html
  src/pages/pagina-da-ong/pagina-da-ong.js
  src/pages/pagina-de-demandas/pagina-de-demandas.css
  src/pages/pagina-de-demandas/pagina-de-demandas.html
  src/pages/pagina-de-demandas/pagina-de-demandas.js
Labels: enhancement

#279 Adiciona definições do dominio sessões.
  db.json
  docs/development.md
  src/js/models/session.js
Labels: enhancement

#282 Correção db.json
  db.json
Labels: enhancement

#285 Adiciona teste de Responsividade
  docs/tests.md
Labels: documentation
