Repository ICEI-PUC-Minas-PMV-SI/pmv-si-2023-2-pe1-t2-conecta, pull requests merged in 2023-12, with the labels that each got.

#283 Authentication
  src/components/header/header.js
  src/js/http.js
  src/js/models/organization.js
  src/js/models/session.js
  src/js/utils.js
  src/pages/cadastrar-ong/cadastrar-ong-1.html
  src/pages/cadastrar-ong/cadastrar-ong-1.js
  src/pages/cadastrar-ong/cadastrar-ong-2.html
  src/pages/cadastrar-ong/cadastrar-ong-2.js
  src/pages/login/login.html
  src/pages/login/login.js
  src/pages/pagina-da-ong/pagina-da-ong.html
  src/pages/pagina-da-ong/pagina-da-ong.js
Labels: enhancement

#276 Funcionalidade: Recuperação de senha
  docs/tests.md
  src/js/constants.js
  src/js/envio-email.js
  src/js/models/organization.js
  src/pages/login/login.html
  src/pages/login/login.js
  src/pages/recuperar-senha/recuperar-senha.html
  src/pages/recuperar-senha/recuperar-senha.js
Labels: enhancement

#280 Funcionalidade: Listar demandas
  docs/tests.md
  src/components/horizontal-task-card/horizontal-task-card.js
  src/components/vertical-task-card/vertical-task-card.js
  src/js/modal.js
  src/js/models/task.js
  src/pages/pagina-da-ong/pagina-da-ong.html
  src/pages/pagina-da-ong/pagina-da-ong.js
  src/pages/pagina-de-demandas/pagina-de-demandas.html
  src/pages/pagina-de-demandas/pagina-de-demandas.js
Labels: enhancement

#288 CT15 - Página "Perguntas Frequentes"
  docs/tests.md
Labels: documentation

#289 CT24: Disponibilização de Depoimentos no Perfil da ONG
  docs/tests.md
Labels: documentation

#291 CT17 - Página "Sobre o Voluntariado" e CT19 - Página "Histórias de Sucesso"
  docs/tests.md
Labels: documentation

#292 CT31 - Compatibilidade com Navegadores
  docs/tests.md
Labels: documentation

#293 CT14 - Página "Como Começar"
  docs/tests.md
Labels: documentation

#290 CT15 - Página Inicial (Landing Page)
  docs/tests.md
  src/components/footer/footer.js
  src/components/vertical-task-card/vertical-task-card.js
  src/index.html
  src/js/http.js
  src/js/landing-page.js
  src/js/modal.js
  src/js/slide.js
  src/pages/pagina-da-ong/pagina-da-ong.css
Labels: documentation, enhancement

#305 CT27 - Interface simples
  docs/tests.md
Labels: documentation

#304 Cenários para teste de usabilidade
  docs/tests.md
Labels: documentation

#296 Página: Administrar uma demanda
  src/js/models/candidate.js
  src/js/models/task.js
  src/pages/administrar-demanda-em-progresso/administrar-demanda-em-progresso.html
  src/pages/administrar-demanda-em-progresso/administrar-demanda-em-progresso.js
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.css
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.html
  src/pages/administrar-demanda-finalizada/administrar-demanda-finalizada.js
  src/pages/administrar-demanda/administrar-demanda.css
  src/pages/administrar-demanda/administrar-demanda.html
  src/pages/administrar-demanda/administrar-demanda.js
Labels: enhancement

#294 CT28 - Criptografia de senha
  docs/tests.md
Labels: documentation

#300 altera development
  docs/development.md
Labels: documentation

#297 Adiciona funcionalidade de logout.
  src/components/header/header.js
  src/pages/cadastrar-ong/cadastrar-ong-1.js
  src/pages/cadastrar-ong/cadastrar-ong-2.js
Labels: enhancement

#299 Altera db.json
  db.json
Labels: documentation, enhancement

#303 Adiciona funcionalidade cadastrar e editar demandas.
  src/js/models/task.js
  src/pages/cadastrar-demanda/cadastrar-demanda.html
  src/pages/cadastrar-demanda/cadastrar-demanda.js
Labels: enhancement

#312 Coloca letra maiúscula
  src/js/landing-page.js
  src/pages/pagina-da-ong/pagina-da-ong.js
Labels: enhancement

#311 Adiciona o menu administrar demandas na vr desktop.
  src/components/header/header.js
Labels: enhancement

#308 CT20 - Filtro de Demandas por Critérios- validar filtro em pagina-de-demandas
  docs/tests.md
  src/js/http.js
  src/js/models/task.js
  src/pages/pagina-de-demandas/pagina-de-demandas.css
  src/pages/pagina-de-demandas/pagina-de-demandas.html
  src/pages/pagina-de-demandas/pagina-de-demandas.js
Labels: documentation, enhancement

#313 Cadastrar depoimento
  src/js/models/review.js
  src/js/models/task.js
  src/pages/administrar-demanda/administrar-demanda.js
  src/pages/cadastrar-depoimento/cadastrar-depoimento.html
  src/pages/cadastrar-depoimento/cadastrar-depoimento.js
Labels: enhancement

#325 Otimiza a busca pelas demandas
  src/index.html
  src/js/landing-page.js
  src/js/models/task.js
Labels: enhancement

#326 Several fixes
  src/components/header/header.js
  src/js/landing-page.js
  src/js/models/review.js
  src/pages/administrar-demanda/administrar-demanda.js
  src/pages/administrar-demandas/administrar-demandas.html
  src/pages/administrar-demandas/administrar-demandas.js
  src/pages/pagina-da-ong/pagina-da-ong.js
  src/pages/pagina-de-demandas/pagina-de-demandas.js
Labels: bug

#329 Corrige bug que validava CNPJ em editar perfil
  src/js/models/organization.js
  src/pages/cadastrar-ong/cadastrar-ong-2.js
Labels: bug

#330 Adiciona botão para editar perfil no menu mobile
  src/components/header/header.js
Labels: bug

#331 Corrige bug que evitava editar demanda existente
  src/pages/administrar-demanda/administrar-demanda.html
  src/pages/administrar-demanda/administrar-demanda.js
  src/pages/administrar-demandas/administrar-demandas.js
  src/pages/cadastrar-demanda/cadastrar-demanda.js
Labels: bug

#333 Corrige editar demanda alterando organizationId da task para sessionId
  src/pages/cadastrar-demanda/cadastrar-demanda.js
Labels: bug

#336 Informações do candidato.
  src/pages/administrar-demanda/administrar-demanda.css
  src/pages/administrar-demanda/administrar-demanda.html
  src/pages/administrar-demanda/administrar-demanda.js
Labels: enhancement

#335 Fixing cadastrar depoimento
  src/pages/administrar-demanda/administrar-demanda.js
  src/pages/cadastrar-depoimento/cadastrar-depoimento.js
Labels: bug

#342 adiciona img estatica
  src/pages/cadastrar-ong/cadastrar-ong-2.js
Labels: bug

#343 Corrige link para página da ONG do card
  src/js/landing-page.js
Labels: bug

#345 Adiciona cursor pointer no card
  src/pages/administrar-demanda/administrar-demanda.css
Labels: bug

#344 Ajuste de link social
  src/pages/cadastrar-ong/cadastrar-ong-2.html
  src/pages/cadastrar-ong/cadastrar-ong-2.js
Labels: bug

#347 Adiciona cursor pointer no botão de reabrir demanda
  src/pages/administrar-demanda/administrar-demanda.css
Labels: bug

#318 Realizando testes - em progresso
  docs/tests.md
Labels: documentation

#349 Corrige formatação da tabela de development.md
  docs/development.md
Labels: documentation

#350 Adiciona alterações Header Menu e Mobile Menu
  docs/especification.md
  src/assets/icons/dot-black.png
  src/assets/icons/edit.png
  src/assets/icons/log-out.png
  src/assets/icons/setting.png
  src/components/header/header.js
Labels: enhancement

#356 adiciona favicon
  src/assets/icons/favicon.ico
  src/index.html
  src/pages/administrar-demanda/administrar-demanda.html
  src/pages/administrar-demandas/administrar-demandas.html
  src/pages/cadastrar-demanda/cadastrar-demanda.html
  src/pages/cadastrar-depoimento/cadastrar-depoimento.html
  src/pages/cadastrar-ong/cadastrar-ong-1.html
  src/pages/cadastrar-ong/cadastrar-ong-2.html
  src/pages/candidatar-a-demanda/candidatar-a-demanda.html
  src/pages/como-comecar/como-comecar.html
  src/pages/historias-sucesso/historias-sucesso.html
  src/pages/login/login.html
  src/pages/pagina-da-ong/pagina-da-ong.html
  src/pages/pagina-de-demandas/pagina-de-demandas.html
  src/pages/perguntas-frequentes/perguntas-frequentes.html
  src/pages/por-que-ser-voluntario/por-que-ser-voluntario.html
  src/pages/recuperar-senha/recuperar-senha.html
  src/pages/sobre-o-voluntariado/sobre-o-voluntariado.html
Labels: enhancement
